#!/usr/bin/env sh

export URL_DOWNLOAD=http://tui.home/trafikito/

./trafikito_agent_install.sh --api_key=bcdfcfb21aaceebd99882a55155f3f3bb9589ba6L1 --workspace_id=4c3c20fb-6542-4c96-a736-e54a1240ec8a
