#!/usr/bin/env sh

# /*
#  * Copyright (C) Trafikito.com
#  * All rights reserved.
#  *
#  * Redistribution and use in source and binary forms, with or without
#  * modification, are permitted provided that the following conditions
#  * are met:
#  * 1. Redistributions of source code must retain the above copyright
#  *    notice, this list of conditions and the following disclaimer.
#  * 2. Redistributions in binary form must reproduce the above copyright
#  *    notice, this list of conditions and the following disclaimer in the
#  *    documentation and/or other materials provided with the distribution.
#  *
#  * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
#  * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
#  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  * SUCH DAMAGE.
#  */

# SYNOPSIS: script to reconfigure trafikito.app

#TODO BASEDIR="${0%/*}"
BASEDIR=tmp/trafikito
echo $BASEDIR

# source config and libraries
. $BASEDIR/trafikito.cfg    || exit 1
. $BASEDIR/lib/packages.lib || exit 1
. $BASEDIR/lib/transfer.lib || exit 1

# build new executables.lib
EXECUTE=$BASEDIR/lib/excecutables.lib
>$EXECUTE

###########################################
echo "Looking for tools to run commands..."
###########################################
TOOLLIST="df free grep hostname lsof netstat sed top uptime vmstat"
for tool in $TOOLLIST; do
    x=`which $tool`
    if [ -z "$x" ]; then
        echo "  ERROR: $tool not found"
        installBinary $tool
    else
        echo "  found $x"
        echo "export x_$tool=$x" >>$EXECUTE
    fi
done
