#!/usr/bin/env sh

# /*
#  * Copyright (C) Trafikito.com
#  * All rights reserved.
#  *
#  * Redistribution and use in source and binary forms, with or without
#  * modification, are permitted provided that the following conditions
#  * are met:
#  * 1. Redistributions of source code must retain the above copyright
#  *    notice, this list of conditions and the following disclaimer.
#  * 2. Redistributions in binary form must reproduce the above copyright
#  *    notice, this list of conditions and the following disclaimer in the
#  *    documentation and/or other materials provided with the distribution.
#  *
#  * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
#  * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
#  * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  * SUCH DAMAGE.
#  */

# SYNOPSIS: The trafikito agent

export AGENT_VERSION=10   # TODO

BASEDIR="${0%/*}"
BASEDIR=tmp/trafikito  # TODO
INTERVAL=60   # run every minute

# run without $PATH
#unset PATH

# source config to get time constraints
. $BASEDIR/etc/trafikito.cfg || exit 1

DOSTART=3     # TODO override minute in hour (0..59) at which agent should run to prevent server overload

# calculate time to start
start=`date +%F`
h=`date +%H`
h=`expr $h + 1`
h=`expr $h % 24`
NODELAY=`date +%s -d "${start}T$h:$DOSTART"`

# testing
INTERVAL=5
NODELAY=`date +%s`

while true; do
    start=`date +%s`
    if [ $start -lt $NODELAY ]; then # wait 5 seconds to get closer to DOSTART
        sleep 5
        start=`date +%s`
    fi

    now=`date +%s`
    sleep=$((INTERVAL-now+start))
    if [ $sleep -gt 0 ]; then
        echo "Sleep $sleep"
        #sleep $sleep
    fi

    # source everything else to allow dynamic updates
    . $BASEDIR/lib/set_commands_to_run.sh || exit 1

    # set commands_to_run E.g.: commands_to_run="63e374bd-92be-4275-a985-ba2b8d2a953d,trafikito_uptime,trafikito_total_ram"
    fn_set_commands_to_run
    if [ ! -z "$ERROR" ]; then
        echo $ERROR
        echo "Skipping this run"
        continue
    fi

    # create new tmp file
    >$tmp_file

    # Run commands and send results to tmp file
    fn_execute_all_commands
exit 1

    # collect available commands from available_commands.sh
    fn_collect_available_commands

    # Send outputs to Trafikito API
    fn_send_output_to_trafikito

    # Clean up tmp file
    >$tmp_file

done

exit 1
. "${DIR}/functions/set_os.sh"
. "${DIR}/functions/set_environment.sh"
. "${DIR}/functions/execute_trafikito_cmd.sh"
. "${DIR}/functions/send_output.sh"
. "${DIR}/functions/set_commands_to_run.sh"
. "${DIR}/functions/execute_all_commands.sh"
. "${DIR}/functions/collect_available_commands.sh"

# set agent_version
# set config_file
# set lock_file
# set api_key
# set server_id
# set tmp_file
fn_set_environment

# echo "env set agent_version: $agent_version"
# echo "env set config_file: $config_file"
# echo "env set api_key: $api_key"
# echo "env set server_id: $server_id"
# echo "env set tmp_file: $tmp_file"

# set os
# set os_codename (may be empty string)
# set os_release (may be empty string)
# set centos_flavor (may be empty string)
fn_set_os

if [ ! -r "${DIR}/functions/set_os.sh" ]; then
    echo "Missing agent files. Exiting."
    exit 1;
fi;
if [ ! -r "${DIR}/functions/set_environment.sh" ]; then
    echo "Missing agent files. Exiting."
    exit 1;
fi;
if [ ! -r "${DIR}/functions/execute_trafikito_cmd.sh" ]; then
    echo "Missing agent files. Exiting."
    exit 1;
fi;
if [ ! -r "${DIR}/functions/send_output.sh" ]; then
    echo "Missing agent files. Exiting."
    exit 1;
fi;
if [ ! -r "${DIR}/functions/set_commands_to_run.sh" ]; then
    echo "Missing agent files. Exiting."
    exit 1;
fi;
if [ ! -r "${DIR}/functions/execute_all_commands.sh" ]; then
    echo "Missing agent files. Exiting."
    exit 1;
fi;
if [ ! -r "${DIR}/functions/collect_available_commands.sh" ]; then
    echo "Missing agent files. Exiting."
    exit 1;
fi;


INTERVAL=60  # run every minute

# Don't run all scripts at same time, add some random delay for 1st call
sleep "$random_number"

while true; do

    start=`date +%s`

    now=`date +%s`
    sleep=$((INTERVAL-now+start))
    if [ $sleep -gt 0 ]; then
        sleep $sleep
    fi

    # set commands_to_run E.g.: commands_to_run="63e374bd-92be-4275-a985-ba2b8d2a953d,trafikito_uptime,trafikito_total_ram"
    fn_set_commands_to_run

    # create new tmp file
    >$tmp_file

    # Run commands and send results to tmp file
    fn_execute_all_commands

    # collect available commands from available_commands.sh
    fn_collect_available_commands

    # Send outputs to Trafikito API
    fn_send_output_to_trafikito

    # Clean up tmp file
    >$tmp_file

done
