#!/usr/bin/env sh

export BASEDIR="${0%/*}"

# source config file
. $BASEDIR/etc/trafikito.cfg || exit 1

export AGENTNAME="trafikito_wrapper.sh"

usage() {
    echo "Usage: $0 {start|stop|restart|status}" 1>&2
    exit 1
}

# Get status of an agent server_id
# Returns:
#    0 = running normally
#    1 = not running
# Sets:
#    $PID
getstatus() {
    PID=`pgrep -f "$AGENTNAME $SERVER_ID"`
    return $?
}

# Start an agent server_id
# Parameters:
#    server_id
start() {
    getstatus
    if [ $? -eq 0 ]; then
        set $PID; echo "Trafikito agent already running (pid=$*)" 1>&2
        return
    fi
    if [ $RUNAS = 'nobody' ]; then
        #su -u nobody $BASEDIR/lib/$AGENTNAME $SERVER_ID $BASEDIR &
        su -s /bin/sh -c "$BASEDIR/lib/$AGENTNAME $SERVER_ID $BASEDIR" $RUNAS &
    else
        $BASEDIR/lib/$AGENTNAME $SERVER_ID $BASEDIR &
    fi
    # give agent time to start
    sleep 1
    status
}

# Stop an agent server_id
# Parameters:
#    server_id
stop() {
    getstatus
    if [ $? -ne 0 ]; then
        echo "Trafikito agent stopped" 1>&2
        return
    fi
    kill -9 $PID
    status
}

# Show status for an agent server_id
status() {
    getstatus
    case $? in
        0) set $PID
           echo "Trafikito agent running (pid=$*)" 1>&2
           ;;
        1) echo "Trafikito agent stopped" 1>&2
           echo 1>&2
           tail $BASEDIR/var/trafikito.log 2>/dev/null
           ;;
    esac
}

# need root
if [ $RUNAS = "nobody" ] && [ `whoami` != "root" ]; then
    echo "You must be root to control the Trafikito agent running as the user '$RUNAS'"
    exit 1
fi

if [ $# -ne 1 ]; then
    usage
fi

case $1 in
    start)   start  ;;
    stop)    stop   ;;
    restart) stop; start ;;
    status)  status  ;;
    *) usage
esac
